# Generated by Django 6.0.2 on 2026-02-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostafaraihan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techpost',
            name='image',
        ),
        migrations.CreateModel(
            name='TechImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tech_posts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mostafaraihan.techpost')),
            ],
        ),
    ]
