# Generated by Django 6.0.2 on 2026-02-10 06:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mostafaraihan', '0002_remove_techpost_image_techimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
