# Generated by Django 6.0.2 on 2026-02-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostafaraihan', '0003_alter_techimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='techpost',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='techpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
